language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - tools # Running this twice get's you the latest build tools

before_install:
  - touch /home/travis/.android/repositories.cfg

install:
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "tools" > /dev/null
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-27" > /dev/null # Latest platform required by SDK tools
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository" > /dev/null
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository" > /dev/null
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" > /dev/null
  - echo yes | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" > /dev/null

script:
   - ./gradlew build

licenses:
#  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
#  - 'google-gdk-license-.+'
  - '.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

