language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools # Running this twice get's you the latest build tools
    - platform-tools
    - android-25
    - build-tools-25.0.3
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
#    - extra-android-support
    - addon-google_apis-google-25

script:
   - ./gradlew build

licenses:
#  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
#  - 'google-gdk-license-.+'
  - '.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

