language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - addon-google_apis-google-24
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - android-25

script:
   - ./gradlew build

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

