language: android
jdk:
  - oraclejdk8
android:
  components:
    - addon-google_apis-google-24
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - platform-tools
    - tools

script:
   - ./gradlew build connectedCheck

